<a href="https://colab.research.google.com/github/DerWeiseTeufel/yandexML_summerschool2026/blob/main/HseHachathon.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
import pandas as pd
data_path = userdata.get('path_hse_hack')
df = pd.read_excel(data_path)
df.head()

,id,Регион,Вуз,укрупненная группа,Профиль,"Уровень безработицы в регионе, %, 2017","Уровень безработицы в регионе, %, 2018","Уровень безработицы в регионе, %, 2019","Уровень безработицы в регионе, %, 2020","Уровень безработицы в регионе, %, 2021",...,Средний балл ЕГЭ (бюджет) в вузе 2017,Средний балл ЕГЭ (бюджет) в вузе 2018,Средний балл ЕГЭ (бюджет) в вузе 2019,Средний балл ЕГЭ (бюджет) в вузе 2020,Средний балл ЕГЭ (бюджет) в вузе 2021,Средний балл ЕГЭ (платный прием) в вузе 2017,Средний балл ЕГЭ (платный прием) в вузе 2018,Средний балл ЕГЭ (платный прием) в вузе 2019,Средний балл ЕГЭ (платный прием) в вузе 2020,Средний балл ЕГЭ (платный прием) в вузе 2021
0,1,Республика Адыгея,Адыгейский государственный университет,Автоматика и управление,классический,9.426,9.206,10.077,10.594,10.046,...,60.666608,62.165769,60.466397,62.936412,62.977097,55.368421,57.704598,57.678313,58.628283,60.830508
1,1,Республика Адыгея,Адыгейский государственный университет,Бизнес-информатика,классический,9.426,9.206,10.077,10.594,10.046,...,60.666608,62.165769,60.466397,62.936412,62.977097,55.368421,57.704598,57.678313,58.628283,60.830508
2,1,Республика Адыгея,Адыгейский государственный университет,Биология,классический,9.426,9.206,10.077,10.594,10.046,...,60.666608,62.165769,60.466397,62.936412,62.977097,55.368421,57.704598,57.678313,58.628283,60.830508
3,1,Республика Адыгея,Адыгейский государственный университет,География,классический,9.426,9.206,10.077,10.594,10.046,...,60.666608,62.165769,60.466397,62.936412,62.977097,55.368421,57.704598,57.678313,58.628283,60.830508
4,1,Республика Адыгея,Адыгейский государственный университет,Дизайн,классический,9.426,9.206,10.077,10.594,10.046,...,60.666608,62.165769,60.466397,62.936412,62.977097,55.368421,57.704598,57.678313,58.628283,60.830508

In [ ]:
df.shape

(7539, 130)

In [ ]:
df.describe()

,id,"Уровень безработицы в регионе, %, 2017","Уровень безработицы в регионе, %, 2018","Уровень безработицы в регионе, %, 2019","Уровень безработицы в регионе, %, 2020","Уровень безработицы в регионе, %, 2021","Средняя номинальная заработная плата в регионе, руб., 2017","Средняя номинальная заработная плата в регионе, руб., 2018","Средняя номинальная заработная плата в регионе, руб., 2019","Средняя номинальная заработная плата в регионе, руб., 2020",...,Средний балл ЕГЭ (бюджет) в вузе 2017,Средний балл ЕГЭ (бюджет) в вузе 2018,Средний балл ЕГЭ (бюджет) в вузе 2019,Средний балл ЕГЭ (бюджет) в вузе 2020,Средний балл ЕГЭ (бюджет) в вузе 2021,Средний балл ЕГЭ (платный прием) в вузе 2017,Средний балл ЕГЭ (платный прием) в вузе 2018,Средний балл ЕГЭ (платный прием) в вузе 2019,Средний балл ЕГЭ (платный прием) в вузе 2020,Средний балл ЕГЭ (платный прием) в вузе 2021
count,7.539000e+03,7539.000000,7539.000000,7539.000000,7539.000000,7539.000000,7539.000000,7539.000000,7539.000000,7539.000000,...,7539.000000,7539.000000,7539.000000,7539.000000,7539.000000,7539.000000,7539.000000,7539.000000,7539.000000,7539.000000
mean,5.753965e+06,6.818675,6.393294,6.854910,8.113814,6.599816,36195.575386,39990.520401,43431.258192,46310.611170,...,64.951204,66.118859,67.529610,68.481253,67.966436,55.806660,57.434754,57.741247,59.780719,60.871073
std,6.163888e+07,3.546150,3.411584,3.585443,4.153088,3.702208,12402.190051,13889.959215,15434.018458,16224.294614,...,11.851316,10.848036,10.649664,10.766733,10.808033,13.649891,10.776272,12.187047,12.650425,9.985649
min,1.000000e+00,2.377843,2.119263,2.616504,3.975000,3.007000,21796.792754,24764.074202,27029.575000,28173.208333,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.170000e+02,4.835000,4.563000,5.209000,5.546000,4.322000,27484.149444,30380.238263,32834.291667,35049.458333,...,60.329360,61.275424,61.988967,63.712938,63.392588,54.203394,54.585414,55.160440,57.804167,58.649765
50%,2.570000e+02,6.674000,6.143000,6.368000,7.359000,5.763000,31276.022392,35034.706171,37203.033333,39053.941667,...,65.056642,66.053018,67.295596,68.300000,67.321507,58.145652,58.513287,59.275991,61.771313,61.775726
75%,1.563000e+03,7.925000,7.874000,8.212000,8.935000,7.412000,40983.713399,45127.084963,49453.675000,52466.200000,...,70.638079,71.657370,73.292963,74.091162,73.501815,61.511397,61.993159,62.872689,64.510263,64.582857
max,6.666692e+08,26.914000,26.905000,27.859000,31.215000,32.456000,74809.067767,86111.494425,93119.683333,102478.116667,...,96.400000,96.384321,97.316364,97.586358,97.102845,83.579699,86.305926,88.614384,89.193993,89.500000

In [ ]:
#CONSTANTS
PERMANENT_COLS = ['Регион' ,'Вуз' 	,'укрупненная группа', 	'Профиль']
COLS_2017 = list(df.columns[df.columns.str.endswith('2017')])
COLS_2018 = list(df.columns[df.columns.str.endswith('2018')])
COLS_2019 = list(df.columns[df.columns.str.endswith('2019')])
COLS_2020 = list(df.columns[df.columns.str.endswith('2020')])
COLS_2021 = list(df.columns[df.columns.str.endswith('2021')])

In [ ]:
len(PERMANENT_COLS) + len(COLS_2017) + len(COLS_2018) + len(COLS_2019) + len(COLS_2020) + len(COLS_2021) # the right number

129

# EDA

In [ ]:
df[PERMANENT_COLS]

,Регион,Вуз,укрупненная группа,Профиль
0,Республика Адыгея,Адыгейский государственный университет,Автоматика и управление,классический
1,Республика Адыгея,Адыгейский государственный университет,Бизнес-информатика,классический
2,Республика Адыгея,Адыгейский государственный университет,Биология,классический
3,Республика Адыгея,Адыгейский государственный университет,География,классический
4,Республика Адыгея,Адыгейский государственный университет,Дизайн,классический
...,...,...,...,...
7534,Костромская область,Костромской государственный технологический ун...,Управление качеством,технический
7535,Костромская область,Костромской государственный технологический ун...,Экология,технический
7536,Костромская область,Костромской государственный технологический ун...,Экономика,технический
7537,Костромская область,Костромской государственный технологический ун...,Энергетика и энергетическое машиностроение,технический
7538,Костромская область,Костромской государственный технологический ун...,Юриспруденция,технический

In [ ]:
values_perm_cols = {}
for col in PERMANENT_COLS:
  values_perm_cols[col] = df[col].value_counts()

In [ ]:
values_perm_cols

{'Регион': Регион
 Москва и Московская область     940
 Санкт-Петербург                 452
 Самарская область               183
 Новосибирская область           180
 Ростовская область              171
                                ...
 Еврейская автономная область     24
 Республика Хакасия               22
 Республика Алтай                 22
 Республика Ингушетия             21
 Магаданская область              14
 Name: count, Length: 79, dtype: int64,
 'Вуз': Вуз
 Дальневосточный федеральный университет                               60
 Сибирский федеральный университет                                     55
 Орловский государственный университет им. И.С. Тургенева              54
 Южный федеральный университет                                         53
 Северный (Арктический) федеральный университет им. М.В. Ломоносова    52
                                                                       ..
 Северо-Осетинская государственная медицинская академия                 1
 Ижевская государственная медицинская академия                          1
 Государственный институт русского языка им. А.С. Пушкина               1
 Дагестанский государственный медицинский университет                   1
 Читинская государственная медицинская академия                         1
 Name: count, Length: 405, dtype: int64,
 'укрупненная группа': укрупненная группа
 Менеджмент                                        341
 Экономика                                         309
 Информатика и вычислительная техника              301
 Экология                                          259
 Сфера обслуживания                                249
                                                  ...
 Управление водным транспортом                      14
 Актерское исполнительство                          14
 Постановка действа (художественная постановка)     13
 Искусства и гуманитарные науки                     12
 Кинооператорство                                    2
 Name: count, Length: 75, dtype: int64,
 'Профиль': Профиль
 классический               3160
 технический                2498
 педагогический              597
 аграрный                    575
 социально-экономический     543
 медицинский                 166
 Name: count, dtype: int64}

In [ ]:
import plotly.graph_objects as go
import plotly.express as px

def create_barchart(counts, names, title="Bar Chart", xaxis_title="Categories", yaxis_title="Counts",
                   color=None, show_values=True, horizontal=False, template="plotly_white"):
    """
    Create a bar chart from lists of counts and names using Plotly.

    Parameters:
    -----------
    counts : list
        List of numerical values for the bar heights
    names : list
        List of category names for the x-axis
    title : str, optional
        Chart title (default: "Bar Chart")
    xaxis_title : str, optional
        X-axis title (default: "Categories")
    yaxis_title : str, optional
        Y-axis title (default: "Counts")
    color : str or list, optional
        Color for bars. Can be a single color or list of colors (default: None - uses default colors)
    show_values : bool, optional
        Whether to display values on top of bars (default: True)
    horizontal : bool, optional
        Whether to create horizontal bars instead of vertical (default: False)
    template : str, optional
        Plotly template (default: "plotly_white")

    Returns:
    --------
    plotly.graph_objects.Figure
        The Plotly figure object
    """

    # Input validation
    if len(counts) != len(names):
        raise ValueError("Counts and names lists must have the same length")

    if not counts or not names:
        raise ValueError("Counts and names lists cannot be empty")

    # Create the bar chart
    if horizontal:
        fig = go.Figure(data=[go.Bar(
            x=counts,
            y=names,
            orientation='h',
            marker_color=color,
            text=counts if show_values else None,
            textposition='auto' if show_values else None,
            hovertemplate='<b>%{y}</b><br>Count: %{x}<extra></extra>'
        )])
    else:
        fig = go.Figure(data=[go.Bar(
            x=names,
            y=counts,
            marker_color=color,
            text=counts if show_values else None,
            textposition='auto' if show_values else None,
            hovertemplate='<b>%{x}</b><br>Count: %{y}<extra></extra>'
        )])

    # Update layout
    fig.update_layout(
        title=title,
        xaxis_title=xaxis_title if not horizontal else yaxis_title,
        yaxis_title=yaxis_title if not horizontal else xaxis_title,
        template=template,
        showlegend=False
    )

    return fig

# Example usage and alternative implementation using Plotly Express
def create_barchart_express(counts, names, title="Bar Chart", xaxis_title="Categories",
                           yaxis_title="Counts", color=None, horizontal=False):
    """
    Alternative implementation using Plotly Express (simpler but less customizable)
    """
    import pandas as pd

    # Create DataFrame
    df = pd.DataFrame({
        'names': names,
        'counts': counts
    })

    if horizontal:
        fig = px.bar(df, y='names', x='counts', title=title, color=color,
                    orientation='h')
        fig.update_layout(xaxis_title=yaxis_title, yaxis_title=xaxis_title)
    else:
        fig = px.bar(df, x='names', y='counts', title=title, color=color)
        fig.update_layout(xaxis_title=xaxis_title, yaxis_title=yaxis_title)

    return fig

In [ ]:
values_perm_cols[PERMANENT_COLS[0]].index

Index(['Москва и Московская область', 'Санкт-Петербург', 'Самарская область',
       'Новосибирская область', 'Ростовская область', 'Республика Татарстан',
       'Свердловская область', 'Челябинская область', 'Иркутская область',
       'Нижегородская область', 'Приморский край', 'Республика Башкортостан',
       'Красноярский край', 'Омская область', 'Воронежская область',
       'Томская область', 'Хабаровский край', 'Краснодарский край',
       'Республика Крым', 'Пермский край', 'Ставропольский край',
       'Волгоградская область', 'Республика Дагестан', 'Саратовская область',
       'Алтайский край', 'Курская область', 'Кемеровская область',
       'Тюменская область', 'Ульяновская область',
       'Ханты-Мансийский автономный округ — Югра', 'Белгородская область',
       'Липецкая область', 'Тамбовская область', 'Удмуртская Республика',
       'Республика Бурятия', 'Ярославская область', 'Астраханская область',
       'Вологодская область', 'Оренбургская область', 'Ивановская область',
       'Республика Северная Осетия — Алания', 'Пензенская область',
       'Брянская область', 'Тульская область', 'Орловская область',
       'Тверская область', 'Калининградская область', 'Мурманская область',
       'Кировская область', 'Чувашская Республика', 'Рязанская область',
       'Республика Саха (Якутия)', 'Республика Марий Эл',
       'Чеченская Республика', 'Архангельская область', 'Владимирская область',
       'Костромская область', 'Республика Коми', 'Амурская область',
       'Республика Мордовия', 'Кабардино-Балкарская Республика',
       'Республика Адыгея', 'Курганская область', 'Забайкальский край',
       'Псковская область', 'Смоленская область', 'Республика Карелия',
       'Новгородская область', 'Карачаево-Черкесская Республика',
       'Камчатский край', 'Калужская область', 'Республика Калмыкия',
       'Республика Тыва', 'Сахалинская область',
       'Еврейская автономная область', 'Республика Хакасия',
       'Республика Алтай', 'Республика Ингушетия', 'Магаданская область'],
      dtype='object', name='Регион')

In [ ]:
fig1 = create_barchart_express(values_perm_cols[PERMANENT_COLS[0]], values_perm_cols[PERMANENT_COLS[0]].index, title="Регионы")
fig1.show()

In [ ]:
", ".join(list(values_perm_cols[PERMANENT_COLS[0]].index))

'Москва и Московская область, Санкт-Петербург, Самарская область, Новосибирская область, Ростовская область, Республика Татарстан, Свердловская область, Челябинская область, Иркутская область, Нижегородская область, Приморский край, Республика Башкортостан, Красноярский край, Омская область, Воронежская область, Томская область, Хабаровский край, Краснодарский край, Республика Крым, Пермский край, Ставропольский край, Волгоградская область, Республика Дагестан, Саратовская область, Алтайский край, Курская область, Кемеровская область, Тюменская область, Ульяновская область, Ханты-Мансийский автономный округ — Югра, Белгородская область, Липецкая область, Тамбовская область, Удмуртская Республика, Республика Бурятия, Ярославская область, Астраханская область, Вологодская область, Оренбургская область, Ивановская область, Республика Северная Осетия — Алания, Пензенская область, Брянская область, Тульская область, Орловская область, Тверская область, Калининградская область, Мурманская область, Кировская область, Чувашская Республика, Рязанская область, Республика Саха (Якутия), Республика Марий Эл, Чеченская Республика, Архангельская область, Владимирская область, Костромская область, Республика Коми, Амурская область, Республика Мордовия, Кабардино-Балкарская Республика, Республика Адыгея, Курганская область, Забайкальский край, Псковская область, Смоленская область, Республика Карелия, Новгородская область, Карачаево-Черкесская Республика, Камчатский край, Калужская область, Республика Калмыкия, Республика Тыва, Сахалинская область, Еврейская автономная область, Республика Хакасия, Республика Алтай, Республика Ингушетия, Магаданская область'

## Добавление федеральных округов

In [ ]:
import pandas as pd

def add_federal_district(df, region_column='Регион'):
    """
    Добавляет колонку 'федокруг' в DataFrame на основе значений региона

    Parameters:
    -----------
    df : pandas.DataFrame
        Исходный DataFrame
    region_column : str
        Название колонки с регионами (по умолчанию 'region_x')

    Returns:
    --------
    pandas.DataFrame
        DataFrame с добавленной колонкой 'федокруг'
    """

    # Словарь для сопоставления регионов с федеральными округами
    federal_districts = {
        'Центральный федеральный округ': [
            'Москва', 'Московская область', 'Белгородская область', 'Брянская область',
            'Владимирская область', 'Воронежская область', 'Ивановская область',
            'Калужская область', 'Костромская область', 'Курская область', 'Липецкая область',
            'Орловская область', 'Рязанская область', 'Смоленская область', 'Тамбовская область',
            'Тверская область', 'Тульская область', 'Ярославская область'
        ],

        'Северо-Западный федеральный округ': [
            'Санкт-Петербург', 'Ленинградская область', 'Архангельская область',
            'Вологодская область', 'Калининградская область', 'Мурманская область',
            'Новгородская область', 'Псковская область', 'Республика Карелия',
            'Республика Коми', 'Ненецкий автономный округ'
        ],

        'Южный федеральный округ': [
            'Ростовская область', 'Астраханская область', 'Волгоградская область',
            'Краснодарский край', 'Республика Адыгея', 'Республика Калмыкия',
            'Республика Крым', 'Севастополь'
        ],

        'Северо-Кавказский федеральный округ': [
            'Ставропольский край', 'Республика Дагестан', 'Республика Ингушетия',
            'Кабардино-Балкарская Республика', 'Карачаево-Черкесская Республика',
            'Республика Северная Осетия — Алания', 'Чеченская Республика'
        ],

        'Приволжский федеральный округ': [
            'Нижегородская область', 'Кировская область', 'Самарская область',
            'Оренбургская область', 'Пензенская область', 'Пермский край',
            'Саратовская область', 'Ульяновская область', 'Республика Башкортостан',
            'Республика Марий Эл', 'Республика Мордовия', 'Республика Татарстан',
            'Удмуртская Республика', 'Чувашская Республика'
        ],

        'Уральский федеральный округ': [
            'Свердловская область', 'Челябинская область', 'Курганская область',
            'Тюменская область', 'Ханты-Мансийский автономный округ — Югра',
            'Ямало-Ненецкий автономный округ'
        ],

        'Сибирский федеральный округ': [
            'Новосибирская область', 'Иркутская область', 'Кемеровская область',
            'Омская область', 'Томская область', 'Алтайский край', 'Красноярский край',
            'Республика Алтай', 'Республика Тыва', 'Республика Хакасия',
            'Забайкальский край', 'Республика Бурятия'
        ],

        'Дальневосточный федеральный округ': [
            'Приморский край', 'Хабаровский край', 'Амурская область', 'Камчатский край',
            'Магаданская область', 'Сахалинская область', 'Еврейская автономная область',
            'Республика Саха (Якутия)', 'Чукотский автономный округ'
        ]
    }

    # Функция для определения федерального округа по региону
    def get_federal_district(region):
        if pd.isna(region):
            return 'Неизвестно'

        region_str = str(region).strip()

        for district, regions in federal_districts.items():
            if region_str in regions:
                return district

        # Если регион не найден, возвращаем 'Неизвестно'
        return 'Неизвестно'

    # Добавляем колонку с федеральным округом
    df['федокруг'] = df[region_column].apply(get_federal_district)

    return df

# Альтернативная версия с более простым словарем (если нужны только указанные регионы)
def add_federal_district_simple(df, region_column='region_x'):
    """
    Упрощенная версия для конкретного списка регионов
    """

    # Сопоставление только для указанных в вопросе регионов
    region_to_district = {
        'Москва': 'Центральный федеральный округ',
        'Московская область': 'Центральный федеральный округ',
        'Санкт-Петербург': 'Северо-Западный федеральный округ',
        'Самарская область': 'Приволжский федеральный округ',
        'Новосибирская область': 'Сибирский федеральный округ',
        'Ростовская область': 'Южный федеральный округ',
        'Республика Татарстан': 'Приволжский федеральный округ',
        'Свердловская область': 'Уральский федеральный округ',
        'Челябинская область': 'Уральский федеральный округ',
        'Иркутская область': 'Сибирский федеральный округ',
        'Нижегородская область': 'Приволжский федеральный округ',
        'Приморский край': 'Дальневосточный федеральный округ',
        'Республика Башкортостан': 'Приволжский федеральный округ',
        'Красноярский край': 'Сибирский федеральный округ',
        'Омская область': 'Сибирский федеральный округ',
        'Воронежская область': 'Центральный федеральный округ',
        'Томская область': 'Сибирский федеральный округ',
        'Хабаровский край': 'Дальневосточный федеральный округ',
        'Краснодарский край': 'Южный федеральный округ',
        'Республика Крым': 'Южный федеральный округ',
        'Пермский край': 'Приволжский федеральный округ',
        'Ставропольский край': 'Северо-Кавказский федеральный округ',
        'Волгоградская область': 'Южный федеральный округ',
        'Республика Дагестан': 'Северо-Кавказский федеральный округ',
        'Саратовская область': 'Приволжский федеральный округ',
        'Алтайский край': 'Сибирский федеральный округ',
        'Курская область': 'Центральный федеральный округ',
        'Кемеровская область': 'Сибирский федеральный округ',
        'Тюменская область': 'Уральский федеральный округ',
        'Ульяновская область': 'Приволжский федеральный округ',
        'Ханты-Мансийский автономный округ — Югра': 'Уральский федеральный округ',
        'Белгородская область': 'Центральный федеральный округ',
        'Липецкая область': 'Центральный федеральный округ',
        'Тамбовская область': 'Центральный федеральный округ',
        'Удмуртская Республика': 'Приволжский федеральный округ',
        'Республика Бурятия': 'Сибирский федеральный округ',
        'Ярославская область': 'Центральный федеральный округ',
        'Астраханская область': 'Южный федеральный округ',
        'Вологодская область': 'Северо-Западный федеральный округ',
        'Оренбургская область': 'Приволжский федеральный округ',
        'Ивановская область': 'Центральный федеральный округ',
        'Республика Северная Осетия — Алания': 'Северо-Кавказский федеральный округ',
        'Пензенская область': 'Приволжский федеральный округ',
        'Брянская область': 'Центральный федеральный округ',
        'Тульская область': 'Центральный федеральный округ',
        'Орловская область': 'Центральный федеральный округ',
        'Тверская область': 'Центральный федеральный округ',
        'Калининградская область': 'Северо-Западный федеральный округ',
        'Мурманская область': 'Северо-Западный федеральный округ',
        'Кировская область': 'Приволжский федеральный округ',
        'Чувашская Республика': 'Приволжский федеральный округ',
        'Рязанская область': 'Центральный федеральный округ',
        'Республика Саха (Якутия)': 'Дальневосточный федеральный округ',
        'Республика Марий Эл': 'Приволжский федеральный округ',
        'Чеченская Республика': 'Северо-Кавказский федеральный округ',
        'Архангельская область': 'Северо-Западный федеральный округ',
        'Владимирская область': 'Центральный федеральный округ',
        'Костромская область': 'Центральный федеральный округ',
        'Республика Коми': 'Северо-Западный федеральный округ',
        'Амурская область': 'Дальневосточный федеральный округ',
        'Республика Мордовия': 'Приволжский федеральный округ',
        'Кабардино-Балкарская Республика': 'Северо-Кавказский федеральный округ',
        'Республика Адыгея': 'Южный федеральный округ',
        'Курганская область': 'Уральский федеральный округ',
        'Забайкальский край': 'Сибирский федеральный округ',
        'Псковская область': 'Северо-Западный федеральный округ',
        'Смоленская область': 'Центральный федеральный округ',
        'Республика Карелия': 'Северо-Западный федеральный округ',
        'Новгородская область': 'Северо-Западный федеральный округ',
        'Карачаево-Черкесская Республика': 'Северо-Кавказский федеральный округ',
        'Камчатский край': 'Дальневосточный федеральный округ',
        'Калужская область': 'Центральный федеральный округ',
        'Республика Калмыкия': 'Южный федеральный округ',
        'Республика Тыва': 'Сибирский федеральный округ',
        'Сахалинская область': 'Дальневосточный федеральный округ',
        'Еврейская автономная область': 'Дальневосточный федеральный округ',
        'Республика Хакасия': 'Сибирский федеральный округ',
        'Республика Алтай': 'Сибирский федеральный округ',
        'Республика Ингушетия': 'Северо-Кавказский федеральный округ',
        'Магаданская область': 'Дальневосточный федеральный округ'
    }

    def get_district(region):
        if pd.isna(region):
            return 'Неизвестно'

        region_str = str(region).strip()
        return region_to_district.get(region_str, 'Неизвестно')

    df['федокруг'] = df[region_column].apply(get_district)

    return df

In [ ]:
df = add_federal_district(df)
df.head()

,id,Регион,Вуз,укрупненная группа,Профиль,"Уровень безработицы в регионе, %, 2017","Уровень безработицы в регионе, %, 2018","Уровень безработицы в регионе, %, 2019","Уровень безработицы в регионе, %, 2020","Уровень безработицы в регионе, %, 2021",...,Средний балл ЕГЭ (бюджет) в вузе 2018,Средний балл ЕГЭ (бюджет) в вузе 2019,Средний балл ЕГЭ (бюджет) в вузе 2020,Средний балл ЕГЭ (бюджет) в вузе 2021,Средний балл ЕГЭ (платный прием) в вузе 2017,Средний балл ЕГЭ (платный прием) в вузе 2018,Средний балл ЕГЭ (платный прием) в вузе 2019,Средний балл ЕГЭ (платный прием) в вузе 2020,Средний балл ЕГЭ (платный прием) в вузе 2021,федокруг
0,1,Республика Адыгея,Адыгейский государственный университет,Автоматика и управление,классический,9.426,9.206,10.077,10.594,10.046,...,62.165769,60.466397,62.936412,62.977097,55.368421,57.704598,57.678313,58.628283,60.830508,Южный федеральный округ
1,1,Республика Адыгея,Адыгейский государственный университет,Бизнес-информатика,классический,9.426,9.206,10.077,10.594,10.046,...,62.165769,60.466397,62.936412,62.977097,55.368421,57.704598,57.678313,58.628283,60.830508,Южный федеральный округ
2,1,Республика Адыгея,Адыгейский государственный университет,Биология,классический,9.426,9.206,10.077,10.594,10.046,...,62.165769,60.466397,62.936412,62.977097,55.368421,57.704598,57.678313,58.628283,60.830508,Южный федеральный округ
3,1,Республика Адыгея,Адыгейский государственный университет,География,классический,9.426,9.206,10.077,10.594,10.046,...,62.165769,60.466397,62.936412,62.977097,55.368421,57.704598,57.678313,58.628283,60.830508,Южный федеральный округ
4,1,Республика Адыгея,Адыгейский государственный университет,Дизайн,классический,9.426,9.206,10.077,10.594,10.046,...,62.165769,60.466397,62.936412,62.977097,55.368421,57.704598,57.678313,58.628283,60.830508,Южный федеральный округ

In [ ]:
import plotly.graph_objects as go
import plotly.express as px
import pandas as pd

def plot_avg_ege_by_district(df, district_col='Федеральный округ',
                            score_col='Средний балл ЕГЭ (совокупный прием) в вузе 2021',
                            title='Средний балл ЕГЭ по федеральным округам',
                            color_scale='Viridis'):
    """
    Считает средний балл ЕГЭ по федеральным округам и строит bar chart

    Parameters:
    -----------
    df : pandas.DataFrame
        DataFrame с данными
    district_col : str
        Название колонки с федеральными округами
    score_col : str
        Название колонки со средним баллом ЕГЭ
    title : str
        Заголовок графика
    color_scale : str
        Цветовая схема Plotly

    Returns:
    --------
    plotly.graph_objects.Figure
        Bar chart с средними баллами по округам
    """

    # Проверяем наличие колонок
    if district_col not in df.columns:
        raise ValueError(f"Колонка '{district_col}' не найдена в DataFrame")
    if score_col not in df.columns:
        raise ValueError(f"Колонка '{score_col}' не найдена в DataFrame")

    # Удаляем строки с пропущенными значениями в нужных колонках
    clean_df = df[[district_col, score_col]].dropna()

    # Группируем по федеральным округам и считаем средний балл
    avg_scores = clean_df.groupby(district_col)[score_col].mean().sort_values(ascending=False)

    # Создаем bar chart с помощью Plotly Graph Objects
    fig = go.Figure(data=[go.Bar(
        x=avg_scores.index,
        y=avg_scores.values,
        text=avg_scores.values.round(2),
        textposition='auto',
        marker_color=avg_scores.values,
        marker_colorscale=color_scale,
        hovertemplate='<b>%{x}</b><br>Средний балл: %{y:.2f}<extra></extra>'
    )])

    # Обновляем layout
    fig.update_layout(
        title=dict(
            text=title,
            x=0.5,
            xanchor='center',
            font=dict(size=16)
        ),
        xaxis_title="Федеральный округ",
        yaxis_title="Средний балл ЕГЭ",
        template="plotly_white",
        showlegend=False,
        height=600,
        xaxis_tickangle=-45
    )

    return fig, avg_scores

# Альтернативная версия с использованием Plotly Express
def plot_avg_ege_by_district_express(df, district_col='Федеральный округ',
                                    score_col='Средний балл ЕГЭ (совокупный прием) в вузе 2021',
                                    title='Средний балл ЕГЭ по федеральным округам'):
    """
    Альтернативная реализация с использованием Plotly Express
    """

    # Проверяем наличие колонок
    if district_col not in df.columns:
        raise ValueError(f"Колонка '{district_col}' не найдена в DataFrame")
    if score_col not in df.columns:
        raise ValueError(f"Колонка '{score_col}' не найдена в DataFrame")

    # Удаляем пропущенные значения и группируем
    clean_df = df[[district_col, score_col]].dropna()
    avg_scores = clean_df.groupby(district_col)[score_col].mean().reset_index()
    avg_scores = avg_scores.sort_values(score_col, ascending=False)

    # Создаем bar chart
    fig = px.bar(
        avg_scores,
        x=district_col,
        y=score_col,
        title=title,
        color=score_col,
        color_continuous_scale='Viridis',
        text=score_col.round(2)
    )

    # Обновляем layout
    fig.update_layout(
        xaxis_title="Федеральный округ",
        yaxis_title="Средний балл ЕГЭ",
        template="plotly_white",
        showlegend=False,
        height=600,
        xaxis_tickangle=-45
    )

    fig.update_traces(
        texttemplate='%{text:.2f}',
        textposition='auto',
        hovertemplate='<b>%{x}</b><br>Средний балл: %{y:.2f}<extra></extra>'
    )

    return fig, avg_scores

# Функция для горизонтального bar chart
def plot_avg_ege_by_district_horizontal(df, district_col='Федеральный округ',
                                       score_col='Средний балл ЕГЭ (совокупный прием) в вузе 2021',
                                       title='Средний балл ЕГЭ по федеральным округам'):
    """
    Горизонтальный bar chart для лучшей читаемости длинных названий
    """

    if district_col not in df.columns:
        raise ValueError(f"Колонка '{district_col}' не найдена в DataFrame")
    if score_col not in df.columns:
        raise ValueError(f"Колонка '{score_col}' не найдена в DataFrame")

    clean_df = df[[district_col, score_col]].dropna()
    avg_scores = clean_df.groupby(district_col)[score_col].mean().sort_values(ascending=True)

    fig = go.Figure(data=[go.Bar(
        y=avg_scores.index,
        x=avg_scores.values,
        orientation='h',
        text=avg_scores.values.round(2),
        textposition='auto',
        marker_color=avg_scores.values,
        marker_colorscale='Viridis',
        hovertemplate='<b>%{y}</b><br>Средний балл: %{x:.2f}<extra></extra>'
    )])

    fig.update_layout(
        title=dict(
            text=title,
            x=0.5,
            xanchor='center',
            font=dict(size=16)
        ),
        xaxis_title="Средний балл ЕГЭ",
        yaxis_title="Федеральный округ",
        template="plotly_white",
        showlegend=False,
        height=600,
        margin=dict(l=100, r=50, t=80, b=50)
    )

    return fig, avg_scores


# Дополнительная функция для расширенной статистики
def analyze_ege_by_district(df, district_col='Федеральный округ',
                           score_col='Средний балл ЕГЭ (совокупный прием) в вузе 2021'):
    """
    Расширенный анализ средних баллов ЕГЭ по федеральным округам
    """

    clean_df = df[[district_col, score_col]].dropna()

    # Полная статистика по группам
    stats = clean_df.groupby(district_col)[score_col].agg([
        'count', 'mean', 'median', 'std', 'min', 'max'
    ]).round(2).sort_values('mean', ascending=False)

    # Общая статистика
    overall_stats = {
        'Общее количество наблюдений': len(clean_df),
        'Общий средний балл': clean_df[score_col].mean(),
        'Медианный балл': clean_df[score_col].median(),
        'Стандартное отклонение': clean_df[score_col].std()
    }

    return stats, overall_stats

stats, overall = analyze_ege_by_district(df, 'федокруг')

print("Расширенная статистика по округам:")
print(stats)
print("\nОбщая статистика:")
for key, value in overall.items():
  print(f"{key}: {value:.2f}")

Расширенная статистика по округам:
                                     count   mean  median    std    min    max
федокруг
Неизвестно                             940  73.59   73.62  10.22   0.00  95.31
Северо-Западный федеральный округ      882  69.25   69.46  10.99   0.00  87.88
Приволжский федеральный округ         1379  66.24   66.76   5.16  48.59  76.24
Уральский федеральный округ            536  65.46   66.13  10.28   0.00  77.98
Сибирский федеральный округ           1092  64.12   65.06   6.46  51.30  84.20
Центральный федеральный округ         1149  64.03   64.69   4.63  48.87  73.45
Южный федеральный округ                659  62.05   63.23  11.66   0.00  75.90
Северо-Кавказский федеральный округ    438  61.90   61.78   5.82  45.51  69.74
Дальневосточный федеральный округ      464  61.15   62.72   6.16  44.99  71.04

Общая статистика:
Общее количество наблюдений: 7539.00
Общий средний балл: 65.88
Медианный балл: 66.08
Стандартное отклонение: 8.85

In [ ]:
fig,_ = plot_avg_ege_by_district_horizontal(df,'федокруг')
fig.show()

In [ ]:
df[COLS_2021].columns

Index(['Уровень безработицы в регионе, %, 2021',
       'Средняя номинальная заработная плата в регионе, руб., 2021',
       'Численность выпускников школ в регионе, чел., 2021',
       'Общая численность студентов, обучающихся по программам бакалавриата, специалитета, магистратуры в вузе, чел., 2021',
       'Общая численность ППС (без внешних совместителей и работающих по договорам ГПХ), чел., 2021',
       'Доходы от НИОКР в расчете на одного НПР в вузе, тыс. руб., 2021',
       'Доходы образовательной организации в расчете на одного НПР, тыс. руб, 2021',
       'Зачислено БВИ на УГН в вузе, чел. 2021',
       'Доля БВИ (от числа бюджетных студентов) на УГН в вузе, %, 2021',
       'Зачислено (совокупный прием) на УГН в вузе, чел. 2021',
       'Зачислено на бюджетные места на УГН в вузе, чел. 2021',
       'Зачислено на платные места на УГН в вузе, чел. 2021',
       'Доля платных студентов на УГН в вузе, %, 2021',
       'Ср.балл ЕГЭ (совокупный прием) на УГН в вузе 2021',
       'Ср.балл ЕГЭ (бюджет) на УГН в вузе 2021',
       'Ср.балл ЕГЭ (платный прием) на УГН в вузе 2021',
       'Зачислено (совокупный прием) в вуз, чел., 2021',
       'Зачислено БВИ в вуз, чел., 2021', 'Доля БВИ в вузе, %, 2021',
       'Зачислено на бюджетные места в вуз, чел., 2021',
       'Зачислено на платные места в вуз, чел., 2021',
       'Доля платных студентов в вузе, %, 2021',
       'Средний балл ЕГЭ (совокупный прием) в вузе 2021',
       'Средний балл ЕГЭ (бюджет) в вузе 2021',
       'Средний балл ЕГЭ (платный прием) в вузе 2021'],
      dtype='object')

In [ ]:
values_perm_cols[PERMANENT_COLS[2]] = df.fillna(0)[PERMANENT_COLS[2]].value_counts()

In [ ]:
values_perm_cols[PERMANENT_COLS[0]].index

Index(['Москва и Московская область', 'Санкт-Петербург', 'Самарская область',
       'Новосибирская область', 'Ростовская область', 'Республика Татарстан',
       'Свердловская область', 'Челябинская область', 'Иркутская область',
       'Нижегородская область', 'Приморский край', 'Республика Башкортостан',
       'Красноярский край', 'Омская область', 'Воронежская область',
       'Томская область', 'Хабаровский край', 'Краснодарский край',
       'Республика Крым', 'Пермский край', 'Ставропольский край',
       'Волгоградская область', 'Республика Дагестан', 'Саратовская область',
       'Алтайский край', 'Курская область', 'Кемеровская область',
       'Тюменская область', 'Ульяновская область',
       'Ханты-Мансийский автономный округ — Югра', 'Белгородская область',
       'Липецкая область', 'Тамбовская область', 'Удмуртская Республика',
       'Республика Бурятия', 'Ярославская область', 'Астраханская область',
       'Вологодская область', 'Оренбургская область', 'Ивановская область',
       'Республика Северная Осетия — Алания', 'Пензенская область',
       'Брянская область', 'Тульская область', 'Орловская область',
       'Тверская область', 'Калининградская область', 'Мурманская область',
       'Кировская область', 'Чувашская Республика', 'Рязанская область',
       'Республика Саха (Якутия)', 'Республика Марий Эл',
       'Чеченская Республика', 'Архангельская область', 'Владимирская область',
       'Костромская область', 'Республика Коми', 'Амурская область',
       'Республика Мордовия', 'Кабардино-Балкарская Республика',
       'Республика Адыгея', 'Курганская область', 'Забайкальский край',
       'Псковская область', 'Смоленская область', 'Республика Карелия',
       'Новгородская область', 'Карачаево-Черкесская Республика',
       'Камчатский край', 'Калужская область', 'Республика Калмыкия',
       'Республика Тыва', 'Сахалинская область',
       'Еврейская автономная область', 'Республика Хакасия',
       'Республика Алтай', 'Республика Ингушетия', 'Магаданская область'],
      dtype='object', name='Регион')

In [ ]:
fig1 = create_barchart_express(values_perm_cols[PERMANENT_COLS[2]], values_perm_cols[PERMANENT_COLS[2]].index, title="Направления")
fig1.show()

In [ ]:
fig1 = create_barchart_express(values_perm_cols[PERMANENT_COLS[3]], values_perm_cols[PERMANENT_COLS[3]].index, title="Укрупненные группы")
fig1.show()

In [ ]:
df[PERMANENT_COLS+ COLS_2021] # есть много пропусков, вероятно это просто нули

,Регион,Вуз,укрупненная группа,Профиль,"Уровень безработицы в регионе, %, 2021","Средняя номинальная заработная плата в регионе, руб., 2021","Численность выпускников школ в регионе, чел., 2021","Общая численность студентов, обучающихся по программам бакалавриата, специалитета, магистратуры в вузе, чел., 2021","Общая численность ППС (без внешних совместителей и работающих по договорам ГПХ), чел., 2021","Доходы от НИОКР в расчете на одного НПР в вузе, тыс. руб., 2021",...,Ср.балл ЕГЭ (платный прием) на УГН в вузе 2021,"Зачислено (совокупный прием) в вуз, чел., 2021","Зачислено БВИ в вуз, чел., 2021","Доля БВИ в вузе, %, 2021","Зачислено на бюджетные места в вуз, чел., 2021","Зачислено на платные места в вуз, чел., 2021","Доля платных студентов в вузе, %, 2021",Средний балл ЕГЭ (совокупный прием) в вузе 2021,Средний балл ЕГЭ (бюджет) в вузе 2021,Средний балл ЕГЭ (платный прием) в вузе 2021
0,Республика Адыгея,Адыгейский государственный университет,Автоматика и управление,классический,10.046,35633.250,1743.0,6667.0,348.0,46.32,...,NaN,738,0,NaN,620,118,1.783452,62.633875,62.977097,60.830508
1,Республика Адыгея,Адыгейский государственный университет,Бизнес-информатика,классический,10.046,35633.250,1743.0,6667.0,348.0,46.32,...,63.7,738,0,NaN,620,118,1.783452,62.633875,62.977097,60.830508
2,Республика Адыгея,Адыгейский государственный университет,Биология,классический,10.046,35633.250,1743.0,6667.0,348.0,46.32,...,95.3,738,0,NaN,620,118,1.783452,62.633875,62.977097,60.830508
3,Республика Адыгея,Адыгейский государственный университет,География,классический,10.046,35633.250,1743.0,6667.0,348.0,46.32,...,NaN,738,0,NaN,620,118,1.783452,62.633875,62.977097,60.830508
4,Республика Адыгея,Адыгейский государственный университет,Дизайн,классический,10.046,35633.250,1743.0,6667.0,348.0,46.32,...,66.0,738,0,NaN,620,118,1.783452,62.633875,62.977097,60.830508
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7534,Костромская область,Костромской государственный технологический ун...,Управление качеством,технический,5.651,34988.925,3046.0,6426.0,417.0,28.42,...,NaN,670,0,NaN,569,101,4.123677,64.358806,64.925308,61.167327
7535,Костромская область,Костромской государственный технологический ун...,Экология,технический,5.651,34988.925,3046.0,6426.0,417.0,28.42,...,NaN,670,0,NaN,569,101,4.123677,64.358806,64.925308,61.167327
7536,Костромская область,Костромской государственный технологический ун...,Экономика,технический,5.651,34988.925,3046.0,6426.0,417.0,28.42,...,NaN,670,0,NaN,569,101,4.123677,64.358806,64.925308,61.167327
7537,Костромская область,Костромской государственный технологический ун...,Энергетика и энергетическое машиностроение,технический,5.651,34988.925,3046.0,6426.0,417.0,28.42,...,NaN,670,0,NaN,569,101,4.123677,64.358806,64.925308,61.167327
7538,Костромская область,Костромской государственный технологический ун...,Юриспруденция,технический,5.651,34988.925,3046.0,6426.0,417.0,28.42,...,NaN,670,0,NaN,569,101,4.123677,64.358806,64.925308,61.167327

In [ ]:
df[df.isna().any(axis=1)]

,id,Регион,Вуз,укрупненная группа,Профиль,"Уровень безработицы в регионе, %, 2017","Уровень безработицы в регионе, %, 2018","Уровень безработицы в регионе, %, 2019","Уровень безработицы в регионе, %, 2020","Уровень безработицы в регионе, %, 2021",...,Средний балл ЕГЭ (бюджет) в вузе 2017,Средний балл ЕГЭ (бюджет) в вузе 2018,Средний балл ЕГЭ (бюджет) в вузе 2019,Средний балл ЕГЭ (бюджет) в вузе 2020,Средний балл ЕГЭ (бюджет) в вузе 2021,Средний балл ЕГЭ (платный прием) в вузе 2017,Средний балл ЕГЭ (платный прием) в вузе 2018,Средний балл ЕГЭ (платный прием) в вузе 2019,Средний балл ЕГЭ (платный прием) в вузе 2020,Средний балл ЕГЭ (платный прием) в вузе 2021
0,1,Республика Адыгея,Адыгейский государственный университет,Автоматика и управление,классический,9.426,9.206,10.077,10.594,10.046,...,60.666608,62.165769,60.466397,62.936412,62.977097,55.368421,57.704598,57.678313,58.628283,60.830508
1,1,Республика Адыгея,Адыгейский государственный университет,Бизнес-информатика,классический,9.426,9.206,10.077,10.594,10.046,...,60.666608,62.165769,60.466397,62.936412,62.977097,55.368421,57.704598,57.678313,58.628283,60.830508
2,1,Республика Адыгея,Адыгейский государственный университет,Биология,классический,9.426,9.206,10.077,10.594,10.046,...,60.666608,62.165769,60.466397,62.936412,62.977097,55.368421,57.704598,57.678313,58.628283,60.830508
3,1,Республика Адыгея,Адыгейский государственный университет,География,классический,9.426,9.206,10.077,10.594,10.046,...,60.666608,62.165769,60.466397,62.936412,62.977097,55.368421,57.704598,57.678313,58.628283,60.830508
4,1,Республика Адыгея,Адыгейский государственный университет,Дизайн,классический,9.426,9.206,10.077,10.594,10.046,...,60.666608,62.165769,60.466397,62.936412,62.977097,55.368421,57.704598,57.678313,58.628283,60.830508
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7534,104,Костромская область,Костромской государственный технологический ун...,Управление качеством,технический,7.174,6.348,6.771,7.014,5.651,...,61.843464,64.708176,65.933784,66.250898,64.925308,58.676596,57.167611,56.278713,59.257333,61.167327
7535,104,Костромская область,Костромской государственный технологический ун...,Экология,технический,7.174,6.348,6.771,7.014,5.651,...,61.843464,64.708176,65.933784,66.250898,64.925308,58.676596,57.167611,56.278713,59.257333,61.167327
7536,104,Костромская область,Костромской государственный технологический ун...,Экономика,технический,7.174,6.348,6.771,7.014,5.651,...,61.843464,64.708176,65.933784,66.250898,64.925308,58.676596,57.167611,56.278713,59.257333,61.167327
7537,104,Костромская область,Костромской государственный технологический ун...,Энергетика и энергетическое машиностроение,технический,7.174,6.348,6.771,7.014,5.651,...,61.843464,64.708176,65.933784,66.250898,64.925308,58.676596,57.167611,56.278713,59.257333,61.167327
7538,104,Костромская область,Костромской государственный технологический ун...,Юриспруденция,технический,7.174,6.348,6.771,7.014,5.651,...,61.843464,64.708176,65.933784,66.250898,64.925308,58.676596,57.167611,56.278713,59.257333,61.167327

In [ ]:
df[PERMANENT_COLS + COLS_2017].isna().sum().sort_values(ascending=False).iloc[:]

Зачислено БВИ на УГН в вузе, чел. 2017                                                                                6995
Доля БВИ (от числа бюджетных студентов) на УГН в вузе, %, 2017                                                        6995
Доля БВИ в вузе, %, 2017                                                                                              4304
Ср.балл ЕГЭ (платный прием) на УГН в вузе 2017                                                                        3109
Зачислено на платные места на УГН в вузе, чел. 2017                                                                   3057
Доля платных студентов на УГН в вузе, %, 2017                                                                         3057
Ср.балл ЕГЭ (бюджет) на УГН в вузе 2017                                                                               2635
Зачислено на бюджетные места на УГН в вузе, чел. 2017                                                                 2623
Ср.балл ЕГЭ (совокупный прием) на УГН в вузе 2017                                                                     1777
Зачислено (совокупный прием) на УГН в вузе, чел. 2017                                                                 1759
Доля платных студентов в вузе, %, 2017                                                                                 222
Общая численность студентов, обучающихся по программам бакалавриата, специалитета, магистратуры в вузе, чел., 2017      65
Общая численность ППС (без внешних совместителей и работающих по договорам ГПХ), чел., 2017                             65
Доходы образовательной организации в расчете на одного НПР, тыс. руб, 2017                                              65
Доходы от НИОКР в расчете на одного НПР в вузе, тыс. руб., 2017                                                         65
Численность выпускников школ в регионе, чел., 2017                                                                      60
укрупненная группа                                                                                                       0
Вуз                                                                                                                      0
Уровень безработицы в регионе, %, 2017                                                                                   0
Профиль                                                                                                                  0
Регион                                                                                                                   0
Средняя номинальная заработная плата в регионе, руб., 2017                                                               0
Зачислено (совокупный прием) в вуз, чел., 2017                                                                           0
Зачислено на бюджетные места в вуз, чел., 2017                                                                           0
Зачислено БВИ в вуз, чел., 2017                                                                                          0
Зачислено на платные места в вуз, чел., 2017                                                                             0
Средний балл ЕГЭ (совокупный прием) в вузе 2017                                                                          0
Средний балл ЕГЭ (бюджет) в вузе 2017                                                                                    0
Средний балл ЕГЭ (платный прием) в вузе 2017                                                                             0
dtype: int64

In [ ]:
df.head().to_csv('sample.csv')

In [ ]:
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import numpy as np

def prepare_data(df):
    """
    Подготовка данных: преобразование из широкого в длинный формат
    """
    # Создаем списки для разных типов переменных
    years = [2017, 2018, 2019, 2020, 2021]

    # Базовые колонки которые не меняются по годам
    base_columns = ['id', 'Регион', 'Вуз', 'укрупненная группа', 'Профиль']

    # Собираем все данные в длинный формат
    melted_dfs = []

    for year in years:
        year_data = {}

        # Базовые колонки
        for col in base_columns:
            year_data[col] = df[col]

        # Региональные данные
        year_data['Уровень безработицы в регионе, %'] = df[f'Уровень безработицы в регионе, %, {year}']
        year_data['Средняя номинальная заработная плата в регионе, руб.'] = df[f'Средняя номинальная заработная плата в регионе, руб., {year}']
        year_data['Численность выпускников школ в регионе, чел.'] = df[f'Численность выпускников школ в регионе, чел., {year}']

        # Данные по вузу
        year_data['Общая численность студентов в вузе, чел.'] = df[f'Общая численность студентов, обучающихся по программам бакалавриата, специалитета, магистратуры в вузе, чел., {year}']
        year_data['Общая численность ППС, чел.'] = df[f'Общая численность ППС (без внешних совместителей и работающих по договорам ГПХ), чел., {year}']
        year_data['Доходы от НИОКР на НПР, тыс. руб.'] = df[f'Доходы от НИОКР в расчете на одного НПР в вузе, тыс. руб., {year}']
        year_data['Доходы образовательной организации на НПР, тыс. руб'] = df[f'Доходы образовательной организации в расчете на одного НПР, тыс. руб, {year}']

        # Данные по приему на УГН
        year_data['Зачислено БВИ на УГН, чел.'] = df[f'Зачислено БВИ на УГН в вузе, чел. {year}']
        year_data['Доля БВИ на УГН, %'] = df[f'Доля БВИ (от числа бюджетных студентов) на УГН в вузе, %, {year}']
        year_data['Зачислено (совокупный прием) на УГН, чел.'] = df[f'Зачислено (совокупный прием) на УГН в вузе, чел. {year}']
        year_data['Зачислено на бюджетные места на УГН, чел.'] = df[f'Зачислено на бюджетные места на УГН в вузе, чел. {year}']
        year_data['Зачислено на платные места на УГН, чел.'] = df[f'Зачислено на платные места на УГН в вузе, чел. {year}']
        year_data['Доля платных студентов на УГН, %'] = df[f'Доля платных студентов на УГН в вузе, %, {year}']
        year_data['Ср.балл ЕГЭ (совокупный) на УГН'] = df[f'Ср.балл ЕГЭ (совокупный прием) на УГН в вузе {year}']
        year_data['Ср.балл ЕГЭ (бюджет) на УГН'] = df[f'Ср.балл ЕГЭ (бюджет) на УГН в вузе {year}']
        year_data['Ср.балл ЕГЭ (платный) на УГН'] = df[f'Ср.балл ЕГЭ (платный прием) на УГН в вузе {year}']

        # Данные по приему в целом по вузу
        year_data['Зачислено (совокупный прием) в вуз, чел.'] = df[f'Зачислено (совокупный прием) в вуз, чел., {year}']
        year_data['Зачислено БВИ в вуз, чел.'] = df[f'Зачислено БВИ в вуз, чел., {year}']
        year_data['Доля БВИ в вузе, %'] = df[f'Доля БВИ в вузе, %, {year}']
        year_data['Зачислено на бюджетные места в вуз, чел.'] = df[f'Зачислено на бюджетные места в вуз, чел., {year}']
        year_data['Зачислено на платные места в вуз, чел.'] = df[f'Зачислено на платные места в вуз, чел., {year}']
        year_data['Доля платных студентов в вузе, %'] = df[f'Доля платных студентов в вузе, %, {year}']
        year_data['Средний балл ЕГЭ (совокупный) в вузе'] = df[f'Средний балл ЕГЭ (совокупный прием) в вузе {year}']
        year_data['Средний балл ЕГЭ (бюджет) в вузе'] = df[f'Средний балл ЕГЭ (бюджет) в вузе {year}']
        year_data['Средний балл ЕГЭ (платный) в вузе'] = df[f'Средний балл ЕГЭ (платный прием) в вузе {year}']

        year_data['Год'] = year

        melted_df = pd.DataFrame(year_data)
        melted_dfs.append(melted_df)

    final_df = pd.concat(melted_dfs, ignore_index=True)

    # Очистка от пропусков в ключевых переменных
    final_df = final_df.dropna(subset=['Ср.балл ЕГЭ (бюджет) на УГН', 'Зачислено (совокупный прием) на УГН, чел.'])

    return final_df

def plot_avg_scores_trends(df, level='вуз', top_n=10):
    """
    Тренды среднего балла ЕГЭ по годам
    level: 'вуз' или 'регион'
    """
    if level == 'вуз':
        group_col = 'Вуз'
        title = "Динамика среднего балла ЕГЭ по вузам (топ-10 по баллу 2021)"
    else:
        group_col = 'Регион'
        title = "Динамика среднего балла ЕГЭ по регионам"

    # Фильтруем данные за 2021 для определения топовых
    latest_data = df[df['Год'] == 2021]

    if level == 'вуз':
        top_entities = latest_data.groupby(group_col)['Средний балл ЕГЭ (бюджет) в вузе'].mean().nlargest(top_n).index
    else:
        top_entities = latest_data.groupby(group_col)['Средний балл ЕГЭ (бюджет) в вузе'].mean().nlargest(top_n).index

    filtered_df = df[df[group_col].isin(top_entities)]

    fig = px.line(filtered_df,
                  x='Год',
                  y='Средний балл ЕГЭ (бюджет) в вузе',
                  color=group_col,
                  title=title,
                  labels={'Средний балл ЕГЭ (бюджет) в вузе': 'Средний балл ЕГЭ (бюджет)'})

    fig.update_layout(height=500)
    return fig

def plot_admission_quality_heatmap(df, year=2021):
    """
    Heatmap: качество приема vs масштаб приема по направлениям
    """
    current_year_df = df[df['Год'] == year].copy()

    # Агрегируем по направлениям
    direction_stats = current_year_df.groupby('укрупненная группа').agg({
        'Ср.балл ЕГЭ (бюджет) на УГН': 'mean',
        'Зачислено (совокупный прием) на УГН, чел.': 'sum',
        'Доля платных студентов на УГН, %': 'mean'
    }).reset_index()

    direction_stats = direction_stats.dropna()

    fig = px.scatter(direction_stats,
                     x='Зачислено (совокупный прием) на УГН, чел.',
                     y='Ср.балл ЕГЭ (бюджет) на УГН',
                     size='Доля платных студентов на УГН, %',
                     color='Доля платных студентов на УГН, %',
                     hover_name='укрупненная группа',
                     title=f'Качество приема vs Масштаб приема по направлениям ({year} год)',
                     labels={
                         'Зачислено (совокупный прием) на УГН, чел.': 'Число зачисленных',
                         'Ср.балл ЕГЭ (бюджет) на УГН': 'Средний балл ЕГЭ (бюджет)',
                         'Доля платных студентов на УГН, %': 'Доля платных студентов, %'
                     })

    fig.update_layout(height=600)
    return fig

def plot_bvi_analysis(df):
    """
    Анализ доли олимпиадников (БВИ) по годам и направлениям
    """
    # Топ направления по доле БВИ в 2021
    latest_bvi = df[df['Год'] == 2021]
    top_directions = latest_bvi.groupby('укрупненная группа')['Доля БВИ на УГН, %'].mean().nlargest(8).index

    filtered_df = df[df['укрупненная группа'].isin(top_directions)]

    fig = px.box(filtered_df,
                 x='укрупненная группа',
                 y='Доля БВИ на УГН, %',
                 color='Год',
                 title='Распределение доли олимпиадников (БВИ) по топ-направлениям',
                 labels={'Доля БВИ на УГН, %': 'Доля БВИ, %'})

    fig.update_layout(height=500, xaxis_tickangle=45)
    return fig

def plot_regional_analysis(df):
    """
    Анализ влияния региональных факторов на качество приема
    """
    current_data = df[df['Год'] == 2021].dropna(subset=['Средний балл ЕГЭ (бюджет) в вузе',
                                                       'Средняя номинальная заработная плата в регионе, руб.'])

    fig = px.scatter(current_data,
                     x='Средняя номинальная заработная плата в регионе, руб.',
                     y='Средний балл ЕГЭ (бюджет) в вузе',
                     size='Зачислено (совокупный прием) в вуз, чел.',
                     color='Уровень безработицы в регионе, %',
                     hover_name='Вуз',
                     title='Влияние экономических показателей регионов на качество приема (2021)',
                     labels={
                         'Средняя номинальная заработная плата в регионе, руб.': 'Средняя зарплата в регионе',
                         'Средний балл ЕГЭ (бюджет) в вузе': 'Средний балл ЕГЭ (бюджет)',
                         'Уровень безработицы в регионе, %': 'Уровень безработицы, %'
                     })

    fig.update_layout(height=500)
    return fig

def plot_funding_vs_quality(df):
    """
    Анализ связи финансирования и качества приема
    """
    current_data = df[df['Год'] == 2021].dropna(subset=['Средний балл ЕГЭ (бюджет) в вузе',
                                                       'Доходы образовательной организации на НПР, тыс. руб'])

    fig = px.scatter(current_data,
                     x='Доходы образовательной организации на НПР, тыс. руб',
                     y='Средний балл ЕГЭ (бюджет) в вузе',
                     size='Общая численность студентов в вузе, чел.',
                     color='Доходы от НИОКР на НПР, тыс. руб.',
                     hover_name='Вуз',
                     title='Влияние финансирования вузов на качество приема (2021)',
                     labels={
                         'Доходы образовательной организации на НПР, тыс. руб': 'Доходы на одного НПР, тыс. руб',
                         'Средний балл ЕГЭ (бюджет) в вузе': 'Средний балл ЕГЭ (бюджет)',
                         'Доходы от НИОКР на НПР, тыс. руб.': 'Доходы от НИОКР на НПР, тыс. руб'
                     })

    fig.update_layout(height=500)
    return fig

def plot_paid_vs_budget_quality(df):
    """
    Сравнение качества приема на бюджетные и платные места
    """
    comparison_data = df[df['Год'] == 2021].dropna(subset=['Ср.балл ЕГЭ (бюджет) на УГН',
                                                          'Ср.балл ЕГЭ (платный) на УГН'])

    fig = go.Figure()

    fig.add_trace(go.Scatter(
        x=comparison_data['Ср.балл ЕГЭ (бюджет) на УГН'],
        y=comparison_data['Ср.балл ЕГЭ (платный) на УГН'],
        mode='markers',
        marker=dict(
            size=8,
            color=comparison_data['Доля платных студентов на УГН, %'],
            colorscale='Viridis',
            showscale=True,
            colorbar=dict(title="Доля платных<br>студентов, %")
        ),
        #name=comparison_data['Вуз'],
        text=comparison_data[['Вуз', 'укрупненная группа']],
        hovertemplate='<b>%{text}</b><br>Бюджет: %{x:.1f}<br>Платные: %{y:.1f}<br>Доля платных: %{marker.color:.1f}%<extra></extra>'
    ))

    # Добавляем линию равенства
    max_val = max(comparison_data[['Ср.балл ЕГЭ (бюджет) на УГН', 'Ср.балл ЕГЭ (платный) на УГН']].max().max(), 100)
    fig.add_trace(go.Scatter(
        x=[0, max_val], y=[0, max_val],
        mode='lines',
        line=dict(dash='dash', color='gray'),
        name='Линия равенства'
    ))

    fig.update_layout(
        title='Сравнение качества приема на бюджетные и платные места (2021)',
        xaxis_title='Средний балл ЕГЭ (бюджет)',
        yaxis_title='Средний балл ЕГЭ (платные)',
        height=500
    )

    return fig

def plot_admission_dynamics(df, selected_vuz=None, selected_region=None):
    """
    Динамика приема по годам для конкретного вуза или региона
    """
    if selected_vuz:
        filtered_df = df[df['Вуз'] == selected_vuz]
        title = f"Динамика приема в {selected_vuz}"
    elif selected_region:
        filtered_df = df[df['Регион'] == selected_region]
        title = f"Динамика приема в вузах {selected_region}"
    else:
        # Агрегируем по всем вузам
        aggregated = df.groupby('Год').agg({
            'Зачислено (совокупный прием) в вуз, чел.': 'sum',
            'Средний балл ЕГЭ (бюджет) в вузе': 'mean'
        }).reset_index()
        filtered_df = aggregated
        title = "Общая динамика приема по всем вузам"

    fig = make_subplots(specs=[[{"secondary_y": True}]])

    fig.add_trace(
        go.Scatter(x=filtered_df['Год'],
                  y=filtered_df['Зачислено (совокупный прием) в вуз, чел.'],
                  name="Число зачисленных",
                  line=dict(color='blue')),
        secondary_y=False,
    )

    fig.add_trace(
        go.Scatter(x=filtered_df['Год'],
                  y=filtered_df['Средний балл ЕГЭ (бюджет) в вузе'],
                  name="Средний балл ЕГЭ (бюджет)",
                  line=dict(color='red')),
        secondary_y=True,
    )

    fig.update_layout(
        title_text=title,
        height=400
    )

    fig.update_xaxes(title_text="Год")
    fig.update_yaxes(title_text="Число зачисленных", secondary_y=False)
    fig.update_yaxes(title_text="Средний балл ЕГЭ", secondary_y=True)

    return fig

def create_risk_zone_plot(df, year=2021):
    """
    Визуализация 'зоны риска' - вузы/направления с ухудшающимися показателями
    """
    # Вычисляем изменения за последние 2 года
    current_data = df[df['Год'] == year]
    prev_data = df[df['Год'] == year-1]

    # Агрегируем по вузам
    current_agg = current_data.groupby('Вуз').agg({
        'Средний балл ЕГЭ (бюджет) в вузе': 'mean',
        'Зачислено (совокупный прием) в вуз, чел.': 'sum',
        'Регион': 'first'
    }).reset_index()

    prev_agg = prev_data.groupby('Вуз').agg({
        'Средний балл ЕГЭ (бюджет) в вузе': 'mean',
        'Зачислено (совокупный прием) в вуз, чел.': 'sum'
    }).reset_index()

    merged = pd.merge(current_agg, prev_agg, on='Вуз', suffixes=('_current', '_prev'))

    # Вычисляем изменения
    merged['Изменение_балла'] = merged['Средний балл ЕГЭ (бюджет) в вузе_current'] - merged['Средний балл ЕГЭ (бюджет) в вузе_prev']
    merged['Изменение_приема'] = ((merged['Зачислено (совокупный прием) в вуз, чел._current'] -
                                 merged['Зачислено (совокупный прием) в вуз, чел._prev']) /
                                merged['Зачислено (совокупный прием) в вуз, чел._prev'] * 100)

    fig = px.scatter(merged,
                     x='Изменение_приема',
                     y='Изменение_балла',
                     size='Зачислено (совокупный прием) в вуз, чел._current',
                     color='Регион',
                     hover_name='Вуз',
                     title=f'Карта "зоны риска" для вузов ({year} vs {year-1})',
                     labels={
                         'Изменение_приема': 'Изменение приема, %',
                         'Изменение_балла': 'Изменение среднего балла ЕГЭ'
                     })

    # Добавляем линии для разделения квадрантов
    fig.add_hline(y=0, line_dash="dash", line_color="red")
    fig.add_vline(x=0, line_dash="dash", line_color="red")

    # Аннотации для квадрантов
    fig.add_annotation(x=0.5, y=0.9, xref="paper", yref="paper",
                      text="Зона роста", showarrow=False, font=dict(color="green"))
    fig.add_annotation(x=0.5, y=0.1, xref="paper", yref="paper",
                      text="Зона риска", showarrow=False, font=dict(color="red"))

    fig.update_layout(height=600)
    return fig

# Пример использования:
def perform_complete_eda(df):
    """
    Полный EDA анализ данных о приеме в вузы
    """
    # Загрузка данных


    # Подготовка данных
    prepared_df = prepare_data(df)

    # Создание графиков
    plots = {}

    plots['score_trends'] = plot_avg_scores_trends(prepared_df, level='вуз')
    plots['regional_trends'] = plot_avg_scores_trends(prepared_df, level='регион')
    plots['quality_heatmap'] = plot_admission_quality_heatmap(prepared_df)
    plots['bvi_analysis'] = plot_bvi_analysis(prepared_df)
    plots['regional_analysis'] = plot_regional_analysis(prepared_df)
    plots['funding_analysis'] = plot_funding_vs_quality(prepared_df)
    plots['paid_vs_budget'] = plot_paid_vs_budget_quality(prepared_df)
    plots['risk_zone'] = create_risk_zone_plot(prepared_df)

    return prepared_df, plots

# Использование:
# df, plots = perform_complete_eda('sample(1).csv')
# plots['score_trends'].show()
# plots['risk_zone'].show()

In [ ]:
df_result, plots = perform_complete_eda(df)

In [ ]:
plots['score_trends'].show()

Идея: добавить разбивку по ФО, добавить разбивку по квартилям

In [ ]:
plots['risk_zone'].show()

In [ ]:
plots.keys()

dict_keys(['score_trends', 'regional_trends', 'quality_heatmap', 'bvi_analysis', 'regional_analysis', 'funding_analysis', 'paid_vs_budget', 'risk_zone'])

In [ ]:
plots['regional_trends']

In [ ]:
plots['regional_analysis']

In [ ]:
plots['quality_heatmap']

In [ ]:
plots['bvi_analysis']

In [ ]:
plots['funding_analysis']

In [ ]:
plots['paid_vs_budget']

Вузы с низким средним баллом имеют низкую долю студентов платников

In [ ]:
plots['risk_zone']

In [ ]:
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import numpy as np

def prepare_data(df):
    """
    Подготовка данных: преобразование из широкого в длинный формат
    с учетом структуры вашего датасета
    """
    # Базовые колонки которые не меняются по годам
    base_columns = ['id', 'Регион', 'Вуз', 'укрупненная группа', 'Профиль']

    # Собираем все данные в длинный формат
    melted_dfs = []
    years = [2017, 2018, 2019, 2020, 2021]

    for year in years:
        year_data = {}

        # Базовые колонки
        for col in base_columns:
            year_data[col] = df[col]

        # Региональные данные
        year_data['Уровень безработицы в регионе, %'] = df[f'Уровень безработицы в регионе, %, {year}']
        year_data['Средняя номинальная заработная плата в регионе, руб.'] = df[f'Средняя номинальная заработная плата в регионе, руб., {year}']
        year_data['Численность выпускников школ в регионе, чел.'] = df[f'Численность выпускников школ в регионе, чел., {year}']

        # Данные по вузу
        year_data['Общая численность студентов в вузе, чел.'] = df[f'Общая численность студентов, обучающихся по программам бакалавриата, специалитета, магистратуры в вузе, чел., {year}']
        year_data['Общая численность ППС, чел.'] = df[f'Общая численность ППС (без внешних совместителей и работающих по договорам ГПХ), чел., {year}']
        year_data['Доходы от НИОКР на НПР, тыс. руб.'] = df[f'Доходы от НИОКР в расчете на одного НПР в вузе, тыс. руб., {year}']
        year_data['Доходы образовательной организации на НПР, тыс. руб'] = df[f'Доходы образовательной организации в расчете на одного НПР, тыс. руб, {year}']

        # Данные по приему на УГН
        year_data['Зачислено БВИ на УГН, чел.'] = df[f'Зачислено БВИ на УГН в вузе, чел. {year}']
        year_data['Доля БВИ на УГН, %'] = df[f'Доля БВИ (от числа бюджетных студентов) на УГН в вузе, %, {year}']
        year_data['Зачислено (совокупный прием) на УГН, чел.'] = df[f'Зачислено (совокупный прием) на УГН в вузе, чел. {year}']
        year_data['Зачислено на бюджетные места на УГН, чел.'] = df[f'Зачислено на бюджетные места на УГН в вузе, чел. {year}']
        year_data['Зачислено на платные места на УГН, чел.'] = df[f'Зачислено на платные места на УГН в вузе, чел. {year}']
        year_data['Доля платных студентов на УГН, %'] = df[f'Доля платных студентов на УГН в вузе, %, {year}']
        year_data['Ср.балл ЕГЭ (совокупный) на УГН'] = df[f'Ср.балл ЕГЭ (совокупный прием) на УГН в вузе {year}']
        year_data['Ср.балл ЕГЭ (бюджет) на УГН'] = df[f'Ср.балл ЕГЭ (бюджет) на УГН в вузе {year}']
        year_data['Ср.балл ЕГЭ (платный) на УГН'] = df[f'Ср.балл ЕГЭ (платный прием) на УГН в вузе {year}']

        # Данные по приему в целом по вузу
        year_data['Зачислено (совокупный прием) в вуз, чел.'] = df[f'Зачислено (совокупный прием) в вуз, чел., {year}']
        year_data['Зачислено БВИ в вуз, чел.'] = df[f'Зачислено БВИ в вуз, чел., {year}']
        year_data['Доля БВИ в вузе, %'] = df[f'Доля БВИ в вузе, %, {year}']
        year_data['Зачислено на бюджетные места в вуз, чел.'] = df[f'Зачислено на бюджетные места в вуз, чел., {year}']
        year_data['Зачислено на платные места в вуз, чел.'] = df[f'Зачислено на платные места в вуз, чел., {year}']
        year_data['Доля платных студентов в вузе, %'] = df[f'Доля платных студентов в вузе, %, {year}']
        year_data['Средний балл ЕГЭ (совокупный) в вузе'] = df[f'Средний балл ЕГЭ (совокупный прием) в вузе {year}']
        year_data['Средний балл ЕГЭ (бюджет) в вузе'] = df[f'Средний балл ЕГЭ (бюджет) в вузе {year}']
        year_data['Средний балл ЕГЭ (платный) в вузе'] = df[f'Средний балл ЕГЭ (платный прием) в вузе {year}']

        year_data['Год'] = year

        melted_df = pd.DataFrame(year_data)
        melted_dfs.append(melted_df)

    final_df = pd.concat(melted_dfs, ignore_index=True)

    # Заменяем пустые строки и бесконечные значения на NaN
    final_df = final_df.replace([np.inf, -np.inf], np.nan)

    return final_df

def plot_score_distributions(df, year=2021):
    """
    Распределение средних баллов ЕГЭ по типам приема
    """
    current_data = df[df['Год'] == year].dropna(subset=[
        'Ср.балл ЕГЭ (бюджет) на УГН',
        'Ср.балл ЕГЭ (платный) на УГН'
    ], how='all')  # Убираем только если оба столбца пустые

    fig = go.Figure()

    # Добавляем гистограммы только если есть данные
    budget_data = current_data['Ср.балл ЕГЭ (бюджет) на УГН'].dropna()
    paid_data = current_data['Ср.балл ЕГЭ (платный) на УГН'].dropna()

    if len(budget_data) > 0:
        fig.add_trace(go.Histogram(
            x=budget_data,
            name='Бюджетные места',
            opacity=0.7,
            nbinsx=20,
            marker_color='blue'
        ))

    if len(paid_data) > 0:
        fig.add_trace(go.Histogram(
            x=paid_data,
            name='Платные места',
            opacity=0.7,
            nbinsx=20,
            marker_color='red'
        ))

    fig.update_layout(
        title=f'Распределение средних баллов ЕГЭ по типам приема ({year} год)',
        xaxis_title='Средний балл ЕГЭ',
        yaxis_title='Количество направлений',
        barmode='overlay',
        height=500
    )

    return fig

def plot_admission_volume_distribution(df, year=2021):
    """
    Распределение объемов приема по направлениям
    """
    current_data = df[df['Год'] == year].dropna(subset=['Зачислено (совокупный прием) на УГН, чел.'])

    # Убираем выбросы для лучшей визуализации
    Q1 = current_data['Зачислено (совокупный прием) на УГН, чел.'].quantile(0.25)
    Q3 = current_data['Зачислено (совокупный прием) на УГН, чел.'].quantile(0.75)
    IQR = Q3 - Q1
    filtered_data = current_data[
        (current_data['Зачислено (совокупный прием) на УГН, чел.'] >= Q1 - 1.5*IQR) &
        (current_data['Зачислено (совокупный прием) на УГН, чел.'] <= Q3 + 1.5*IQR)
    ]

    fig = px.histogram(filtered_data,
                       x='Зачислено (совокупный прием) на УГН, чел.',
                       nbins=30,
                       title=f'Распределение объемов приема по направлениям ({year} год)',
                       labels={'Зачислено (совокупный прием) на УГН, чел.': 'Число зачисленных'},
                       color_discrete_sequence=['green'])

    fig.update_layout(height=400)

    # Добавляем вертикальную линию для медианы
    median_val = filtered_data['Зачислено (совокупный прием) на УГН, чел.'].median()
    fig.add_vline(x=median_val, line_dash="dash", line_color="red",
                  annotation_text=f"Медиана: {median_val:.0f}")

    return fig

def plot_paid_students_distribution(df, year=2021):
    """
    Распределение доли платных студентов по направлениям
    """
    current_data = df[df['Год'] == year].dropna(subset=['Доля платных студентов на УГН, %'])

    fig = px.histogram(current_data,
                       x='Доля платных студентов на УГН, %',
                       nbins=30,
                       title=f'Распределение доли платных студентов по направлениям ({year} год)',
                       labels={'Доля платных студентов на УГН, %': 'Доля платных студентов, %'},
                       color_discrete_sequence=['orange'])

    fig.update_layout(height=400)

    # Добавляем статистические линии
    mean_val = current_data['Доля платных студентов на УГН, %'].mean()
    median_val = current_data['Доля платных студентов на УГН, %'].median()

    fig.add_vline(x=mean_val, line_dash="dash", line_color="blue",
                  annotation_text=f"Среднее: {mean_val:.1f}%")
    fig.add_vline(x=median_val, line_dash="dash", line_color="red",
                  annotation_text=f"Медиана: {median_val:.1f}%")

    return fig

def plot_bvi_distribution_by_field(df, year=2021, top_n=10):
    """
    Распределение доли БВИ по укрупненным группам направлений
    """
    current_data = df[df['Год'] == year].dropna(subset=['Доля БВИ на УГН, %'])

    # Группируем по направлениям и вычисляем среднюю долю БВИ
    field_bvi = current_data.groupby('укрупненная группа')['Доля БВИ на УГН, %'].mean()

    # Убираем бесконечные значения и сортируем
    field_bvi = field_bvi[field_bvi != np.inf]
    field_bvi = field_bvi.sort_values(ascending=False).head(top_n)

    if len(field_bvi) == 0:
        print("Нет данных о БВИ для построения графика")
        return None

    fig = px.bar(x=field_bvi.index,
                 y=field_bvi.values,
                 title=f'Топ-{len(field_bvi)} направлений по средней доле олимпиадников (БВИ) ({year} год)',
                 labels={'x': 'Укрупненная группа направлений', 'y': 'Средняя доля БВИ, %'},
                 color=field_bvi.values,
                 color_continuous_scale='Viridis')

    fig.update_layout(height=500, xaxis_tickangle=45)
    return fig

def plot_regional_indicators_distribution(df):
    """
    Распределение региональных показателей по годам
    """
    # Фильтруем данные для избежания ошибок
    valid_data = df.dropna(subset=[
        'Уровень безработицы в регионе, %',
        'Средняя номинальная заработная плата в регионе, руб.',
        'Численность выпускников школ в регионе, чел.',
        'Средний балл ЕГЭ (бюджет) в вузе'
    ])

    if len(valid_data) == 0:
        print("Недостаточно данных для построения региональных распределений")
        return None

    fig = make_subplots(rows=2, cols=2,
                        subplot_titles=('Уровень безработицы', 'Средняя зарплата',
                                       'Численность выпускников', 'Качество приема'))

    colors = px.colors.qualitative.Set1

    # Уровень безработицы
    for i, year in enumerate(sorted(valid_data['Год'].unique())):
        year_data = valid_data[valid_data['Год'] == year]['Уровень безработицы в регионе, %'].dropna()
        if len(year_data) > 0:
            fig.add_trace(go.Histogram(
                x=year_data,
                name=str(year),
                opacity=0.6,
                nbinsx=15,
                marker_color=colors[i % len(colors)]
            ), row=1, col=1)

    # Средняя зарплата (в тысячах рублей для лучшего отображения)
    for i, year in enumerate(sorted(valid_data['Год'].unique())):
        year_data = valid_data[valid_data['Год'] == year]['Средняя номинальная заработная плата в регионе, руб.'].dropna() / 1000
        if len(year_data) > 0:
            fig.add_trace(go.Histogram(
                x=year_data,
                name=str(year),
                opacity=0.6,
                nbinsx=15,
                marker_color=colors[i % len(colors)],
                showlegend=False
            ), row=1, col=2)

    # Численность выпускников
    for i, year in enumerate(sorted(valid_data['Год'].unique())):
        year_data = valid_data[valid_data['Год'] == year]['Численность выпускников школ в регионе, чел.'].dropna()
        if len(year_data) > 0:
            fig.add_trace(go.Histogram(
                x=year_data,
                name=str(year),
                opacity=0.6,
                nbinsx=15,
                marker_color=colors[i % len(colors)],
                showlegend=False
            ), row=2, col=1)

    # Качество приема
    for i, year in enumerate(sorted(valid_data['Год'].unique())):
        year_data = valid_data[valid_data['Год'] == year]['Средний балл ЕГЭ (бюджет) в вузе'].dropna()
        if len(year_data) > 0:
            fig.add_trace(go.Histogram(
                x=year_data,
                name=str(year),
                opacity=0.6,
                nbinsx=15,
                marker_color=colors[i % len(colors)],
                showlegend=False
            ), row=2, col=2)

    fig.update_layout(height=600, title_text="Распределение региональных показателей по годам")
    fig.update_xaxes(title_text="Уровень безработицы, %", row=1, col=1)
    fig.update_xaxes(title_text="Средняя зарплата, тыс. руб.", row=1, col=2)
    fig.update_xaxes(title_text="Число выпускников", row=2, col=1)
    fig.update_xaxes(title_text="Средний балл ЕГЭ", row=2, col=2)

    return fig

def plot_score_distribution_by_profile(df, year=2021):
    """
    Распределение баллов ЕГЭ по профилям вузов
    """
    current_data = df[df['Год'] == year].dropna(subset=['Ср.балл ЕГЭ (бюджет) на УГН', 'Профиль'])

    if len(current_data) == 0:
        print("Нет данных для построения распределения по профилям")
        return None

    fig = px.box(current_data,
                 x='Профиль',
                 y='Ср.балл ЕГЭ (бюджет) на УГН',
                 title=f'Распределение баллов ЕГЭ по профилям вузов ({year} год)',
                 labels={'Ср.балл ЕГЭ (бюджет) на УГН': 'Средний балл ЕГЭ (бюджет)'},
                 color='Профиль')

    fig.update_layout(height=500, xaxis_tickangle=45, showlegend=False)
    return fig

def plot_competitive_groups_distribution(df, year=2021):
    """
    Распределение направлений по уровню конкурса
    """
    current_data = df[df['Год'] == year].dropna(subset=['Ср.балл ЕГЭ (бюджет) на УГН', 'Зачислено (совокупный прием) на УГН, чел.'])

    if len(current_data) == 0:
        print("Нет данных для анализа конкурса")
        return None

    # Создаем категории конкурса на основе квартилей
    score_q1 = current_data['Ср.балл ЕГЭ (бюджет) на УГН'].quantile(0.33)
    score_q2 = current_data['Ср.балл ЕГЭ (бюджет) на УГН'].quantile(0.67)

    volume_q1 = current_data['Зачислено (совокупный прием) на УГН, чел.'].quantile(0.33)
    volume_q2 = current_data['Зачислено (совокупный прием) на УГН, чел.'].quantile(0.67)

    def get_competitiveness_group(score, volume):
        if score > score_q2 and volume < volume_q1:
            return 'Высокий конкурс'
        elif score > score_q2 and volume > volume_q2:
            return 'Популярные направления'
        elif score < score_q1 and volume > volume_q2:
            return 'Массовые направления'
        elif score < score_q1 and volume < volume_q1:
            return 'Низкий спрос'
        else:
            return 'Средние показатели'

    current_data['Группа_конкурса'] = current_data.apply(
        lambda row: get_competitiveness_group(
            row['Ср.балл ЕГЭ (бюджет) на УГН'],
            row['Зачислено (совокупный прием) на УГН, чел.']
        ), axis=1
    )

    fig = px.histogram(current_data,
                       x='Группа_конкурса',
                       color='Группа_конкурса',
                       title=f'Распределение направлений по группам конкурса ({year} год)',
                       labels={'Группа_конкурса': 'Группа конкурса'},
                       category_orders={'Группа_конкурса': ['Высокий конкурс', 'Популярные направления',
                                                          'Средние показатели', 'Массовые направления', 'Низкий спрос']})

    fig.update_layout(height=400, showlegend=False)
    return fig

def plot_yearly_comparison_histograms(df, variable, years=[2017, 2018, 2019, 2020, 2021]):
    """
    Сравнительные гистограммы для переменной по годам
    """
    valid_data = df.dropna(subset=[variable])

    if len(valid_data) == 0:
        print(f"Нет данных для переменной {variable}")
        return None

    fig = go.Figure()
    colors = px.colors.qualitative.Set1

    for i, year in enumerate(years):
        year_data = valid_data[valid_data['Год'] == year][variable].dropna()
        if len(year_data) > 0:
            fig.add_trace(go.Histogram(
                x=year_data,
                name=str(year),
                opacity=0.6,
                nbinsx=20,
                marker_color=colors[i % len(colors)]
            ))

    fig.update_layout(
        title=f'Распределение {variable} по годам',
        xaxis_title=variable,
        yaxis_title='Количество',
        barmode='overlay',
        height=500
    )

    return fig

# Функция для выполнения полного анализа распределений
def perform_distribution_analysis(prepared_df):
    """
    Полный анализ распределений ключевых показателей
    """
    plots = {}

    plots['score_distributions'] = plot_score_distributions(prepared_df)
    plots['admission_volume'] = plot_admission_volume_distribution(prepared_df)
    plots['paid_students'] = plot_paid_students_distribution(prepared_df)
    plots['bvi_by_field'] = plot_bvi_distribution_by_field(prepared_df)
    plots['regional_indicators'] = plot_regional_indicators_distribution(prepared_df)
    plots['scores_by_profile'] = plot_score_distribution_by_profile(prepared_df)
    plots['competitive_groups'] = plot_competitive_groups_distribution(prepared_df)

    # Сравнительные гистограммы для ключевых показателей
    plots['yearly_scores'] = plot_yearly_comparison_histograms(prepared_df, 'Ср.балл ЕГЭ (бюджет) на УГН')
    plots['yearly_admission'] = plot_yearly_comparison_histograms(prepared_df, 'Зачислено (совокупный прием) на УГН, чел.')

    return plots

# Пример использования с вашим датасетом:
def load_and_analyze_data(df):
    """
    Загрузка данных и выполнение полного анализа
    """
    # Загрузка данных

    # Подготовка данных
    print("Подготовка данных...")
    prepared_df = prepare_data(df)

    print(f"Подготовлено {len(prepared_df)} записей")
    print(f"Годы в данных: {sorted(prepared_df['Год'].unique())}")
    print(f"Количество вузов: {prepared_df['Вуз'].nunique()}")
    print(f"Количество направлений: {prepared_df['укрупненная группа'].nunique()}")

    # Анализ распределений
    print("Создание графиков...")
    distribution_plots = perform_distribution_analysis(prepared_df)

    return prepared_df, distribution_plots

# Использование:
# prepared_df, plots = load_and_analyze_data('sample(1).csv')
# if plots['score_distributions'] is not None:
#     plots['score_distributions'].show()

In [ ]:
prepared_df, plots = load_and_analyze_data(df)
if plots['score_distributions'] is not None:
       plots['score_distributions'].show()

Подготовка данных...
Подготовлено 37695 записей
Годы в данных: [np.int64(2017), np.int64(2018), np.int64(2019), np.int64(2020), np.int64(2021)]
Количество вузов: 405
Количество направлений: 75
Создание графиков...

In [ ]:
plots['admission_volume']

In [ ]:
plots['paid_students']

In [ ]:
df.head()

,id,Регион,Вуз,укрупненная группа,Профиль,"Уровень безработицы в регионе, %, 2017","Уровень безработицы в регионе, %, 2018","Уровень безработицы в регионе, %, 2019","Уровень безработицы в регионе, %, 2020","Уровень безработицы в регионе, %, 2021",...,Средний балл ЕГЭ (бюджет) в вузе 2017,Средний балл ЕГЭ (бюджет) в вузе 2018,Средний балл ЕГЭ (бюджет) в вузе 2019,Средний балл ЕГЭ (бюджет) в вузе 2020,Средний балл ЕГЭ (бюджет) в вузе 2021,Средний балл ЕГЭ (платный прием) в вузе 2017,Средний балл ЕГЭ (платный прием) в вузе 2018,Средний балл ЕГЭ (платный прием) в вузе 2019,Средний балл ЕГЭ (платный прием) в вузе 2020,Средний балл ЕГЭ (платный прием) в вузе 2021
0,1,Республика Адыгея,Адыгейский государственный университет,Автоматика и управление,классический,9.426,9.206,10.077,10.594,10.046,...,60.666608,62.165769,60.466397,62.936412,62.977097,55.368421,57.704598,57.678313,58.628283,60.830508
1,1,Республика Адыгея,Адыгейский государственный университет,Бизнес-информатика,классический,9.426,9.206,10.077,10.594,10.046,...,60.666608,62.165769,60.466397,62.936412,62.977097,55.368421,57.704598,57.678313,58.628283,60.830508
2,1,Республика Адыгея,Адыгейский государственный университет,Биология,классический,9.426,9.206,10.077,10.594,10.046,...,60.666608,62.165769,60.466397,62.936412,62.977097,55.368421,57.704598,57.678313,58.628283,60.830508
3,1,Республика Адыгея,Адыгейский государственный университет,География,классический,9.426,9.206,10.077,10.594,10.046,...,60.666608,62.165769,60.466397,62.936412,62.977097,55.368421,57.704598,57.678313,58.628283,60.830508
4,1,Республика Адыгея,Адыгейский государственный университет,Дизайн,классический,9.426,9.206,10.077,10.594,10.046,...,60.666608,62.165769,60.466397,62.936412,62.977097,55.368421,57.704598,57.678313,58.628283,60.830508

In [ ]:
df[COLS_2021]

,"Уровень безработицы в регионе, %, 2021","Средняя номинальная заработная плата в регионе, руб., 2021","Численность выпускников школ в регионе, чел., 2021","Общая численность студентов, обучающихся по программам бакалавриата, специалитета, магистратуры в вузе, чел., 2021","Общая численность ППС (без внешних совместителей и работающих по договорам ГПХ), чел., 2021","Доходы от НИОКР в расчете на одного НПР в вузе, тыс. руб., 2021","Доходы образовательной организации в расчете на одного НПР, тыс. руб, 2021","Зачислено БВИ на УГН в вузе, чел. 2021","Доля БВИ (от числа бюджетных студентов) на УГН в вузе, %, 2021","Зачислено (совокупный прием) на УГН в вузе, чел. 2021",...,Ср.балл ЕГЭ (платный прием) на УГН в вузе 2021,"Зачислено (совокупный прием) в вуз, чел., 2021","Зачислено БВИ в вуз, чел., 2021","Доля БВИ в вузе, %, 2021","Зачислено на бюджетные места в вуз, чел., 2021","Зачислено на платные места в вуз, чел., 2021","Доля платных студентов в вузе, %, 2021",Средний балл ЕГЭ (совокупный прием) в вузе 2021,Средний балл ЕГЭ (бюджет) в вузе 2021,Средний балл ЕГЭ (платный прием) в вузе 2021
0,10.046,35633.250,1743.0,6667.0,348.0,46.32,1070.57,NaN,NaN,10.0,...,NaN,738,0,NaN,620,118,1.783452,62.633875,62.977097,60.830508
1,10.046,35633.250,1743.0,6667.0,348.0,46.32,1070.57,NaN,NaN,1.0,...,63.7,738,0,NaN,620,118,1.783452,62.633875,62.977097,60.830508
2,10.046,35633.250,1743.0,6667.0,348.0,46.32,1070.57,NaN,NaN,22.0,...,95.3,738,0,NaN,620,118,1.783452,62.633875,62.977097,60.830508
3,10.046,35633.250,1743.0,6667.0,348.0,46.32,1070.57,NaN,NaN,NaN,...,NaN,738,0,NaN,620,118,1.783452,62.633875,62.977097,60.830508
4,10.046,35633.250,1743.0,6667.0,348.0,46.32,1070.57,NaN,NaN,12.0,...,66.0,738,0,NaN,620,118,1.783452,62.633875,62.977097,60.830508
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7534,5.651,34988.925,3046.0,6426.0,417.0,28.42,524.42,NaN,NaN,NaN,...,NaN,670,0,NaN,569,101,4.123677,64.358806,64.925308,61.167327
7535,5.651,34988.925,3046.0,6426.0,417.0,28.42,524.42,NaN,NaN,NaN,...,NaN,670,0,NaN,569,101,4.123677,64.358806,64.925308,61.167327
7536,5.651,34988.925,3046.0,6426.0,417.0,28.42,524.42,NaN,NaN,NaN,...,NaN,670,0,NaN,569,101,4.123677,64.358806,64.925308,61.167327
7537,5.651,34988.925,3046.0,6426.0,417.0,28.42,524.42,NaN,NaN,NaN,...,NaN,670,0,NaN,569,101,4.123677,64.358806,64.925308,61.167327
7538,5.651,34988.925,3046.0,6426.0,417.0,28.42,524.42,NaN,NaN,NaN,...,NaN,670,0,NaN,569,101,4.123677,64.358806,64.925308,61.167327

In [ ]:
paid_unis = df[df['Доля платных студентов в вузе, %, 2021'] > 80]
print("Направления с самой высокой платностью:")
print(paid_unis['укрупненная группа'].value_counts())

Направления с самой высокой платностью:
укрупненная группа
Государственное и муниципальное управление    1
Информатика и вычислительная техника          1
Менеджмент                                    1
Экономика                                     1
Юриспруденция                                 1
Name: count, dtype: int64

In [ ]:
df[df['Доля платных студентов в вузе, %, 2021'] > 80].shape

(5, 130)